version: "3"

services:
  mydb:
    container_name: mydb
    command: --default-authentication-plugin=mysql_native_password
    build: ./mysql
    environment:
      MYSQL_DATABASE: ours
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    restart: always
    networks:
      - boilerplate-network
    
  php74:
    container_name: php74
    build:
      context: ./php7.4
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./projects/:/var/www/html
      - ./php7.4/conf:/etc/httpd/conf/extra
    depends_on:
      - mydb
    links:
      - mydb
    networks:
      - boilerplate-network
    tty: true
    command: ["/usr/sbin/httpd", "-D", "FOREGROUND"]
  
networks:
  boilerplate-network:
    driver: bridge
