version: "3.3"

services:
  wagokorodb:
    container_name: wagokorodb
    command: mysqld --mysql-native-password=ON
    build: ./mysql
    environment:
      MYSQL_USER: wagokoro
      MYSQL_PASSWORD: wagokoro
      MYSQL_ROOT_PASSWORD: wagokoro
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    restart: always
    networks:
      - boilerplate-network

  php83:
    container_name: php83
    build:
      context: ./php83
      dockerfile: Dockerfile
    volumes:
      - ./../projects/:/var/www/html
    depends_on:
      - wagokorodb
    tty: true
    networks:
      - boilerplate-network
    command: ["/usr/sbin/php-fpm", "--nodaemonize"]
  
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 89:89
      - 90:90
      - 91:91
      - 92:92
      - 93:93
    volumes:
      - ./../projects/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - php83
    networks:
      - boilerplate-network
  
networks:
  boilerplate-network:
    driver: bridge
